myapp/urls.py
from django.urls import path
from myapp import views 
app_name="myapp"

urlpatterns = [
    path('trial/',views.trial,name="trial"),
    path('profile/',views.profile,name="profile"),
    path('get_demo/',views.get_demo,name="get_demo"),
    path('post_demo/',views.post_demo,name="post_demo"),
    path('register/',views.register,name="register"),
    path('multi/',views.multi,name="multiselect"),
    path('img/',views.img_upld,name="img"),
    path('imgdisplay/',views.img_display,name="img_disp"),
    path('upload/',views.upload,name="upload"),
    path('display/',views.display,name="display"),
    path('builtin/',views.builtin,name='builtin')



]

samp9/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

#import settings and static to connect media url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include("myapp.urls")),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
]


if settings.DEBUG==True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

myapp/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms 

choices_day=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]
choices_month=[('1','JAN'),('2','FEB'),('3','MAR'),('4','APR'),('5','MAY'),('6','JUN'),('7','JUL'),('8','AUG'),('9','SEP'),('10','OCT'),('11','NOV'),('12','DEC')]
choices_year=[('1947', '1947'), ('1948', '1948'), ('1949', '1949'), ('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')]


class SampleForm(forms.Form):
  first_name=forms.CharField( max_length=20, required=True,label="First Name",help_text="Note:Space and special chars are not aallowed")
  last_name=forms.CharField( max_length=20, required=False,label="Last Name")
  email=forms.EmailField(max_length=100, required=True,label="Email")
  phno=forms.IntegerField(max_value=9999999999, min_value=6000000000,required=True,label="Phone No.")
  pwd=forms.CharField( max_length=20, required=True,widget=forms.PasswordInput)
  birth_day=forms.ChoiceField( choices=choices_day, required=True,label="Birth Day")
  birth_month=forms.ChoiceField(choices=choices_month,required=True,label="Birth Month")
  birth_year=forms.ChoiceField(choices=choices_year,required=True,label="Birth Year")
  Gender=forms.ChoiceField(choices=[('Male','Male'),('Female','Female'),('other','other')],widget=forms.RadioSelect)
  Image=forms.ImageField(required=True,label='Profile Pic')
  Prog_Languages=forms.MultipleChoiceField(choices=[('C','C'),('C++','C++'),('C#','C#'),('Python','Python'),('Java','Java'),('Ruby','Ruby')],widget=forms.CheckboxSelectMultiple)
  Languages=forms.MultipleChoiceField(choices=[('Telugu','Telugu'),('English','English'),('Kanada','Kanada')],widget=forms.CheckboxSelectMultiple)

myapp/views.py
from django.shortcuts import render,redirect

# Create your views here.
from django.http import HttpResponse
# Create your views here.
def base(request):
  return render(request,"base.html")

def trial(request):
  return HttpResponse("<center><h1>Project is on air</h1></center>")

def home(request):
  return render(request,"myapp/home.html")

def profile(request):
  return render(request,"myapp/profile.html",{"name":"Navya!!!"})

def get_demo(request):
    name=request.GET.get('name')
    return render(request,"get_demo.html",{'name':name})


def post_demo(request):
    if request.method=="POST":
        name=request.POST.get('name')
        return HttpResponse("<h1>Thanks for submission Mr./Ms. {}</h1>".format(name))
    return render(request,"post_demo.html")


from django.core.mail import send_mail

def register(request):
    if request.method=="POST":
        first_name=request.POST.get("first_name")
        last_name=request.POST.get("last_name")
        email=request.POST.get("email")
        password=request.POST.get("pwd")
        phno=request.POST.get("phno")
        date=request.POST.get("birthday_day")
        month=request.POST.get("birthday_month")
        year=request.POST.get("birthday_year")
        gender=request.POST.get("sex")
        if gender=="1":
            gender="FeMale"
        else:
            gender="Male"
        send_mail("Thanks For Registration","hello Mr./Ms.{} {}\n Thanks for Registering".format(first_name,last_name),
        "akshay.python@gmail.com",[email,],fail_silently=True)
        # return HttpResponse("{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>{}<br>".format(first_name,last_name,email,password,phno,gender,date,month,year))
        return redirect("home")
    return render(request,"myapp/register.html")


def multi(request):
    if request.method=="POST":
        foods=request.POST.getlist("food")
        languages=request.POST.getlist("language")
        return HttpResponse("<h1>{}{}<h1>".format(foods,languages))
    return render(request,'multiselect.html')

#uploading and displaying the uploaded image

from django.core.files.storage import FileSystemStorage

def img_upld(request):
     # file_url=False
     # if request.method=="POST" and request.FILES:
     #     image=request.FILES['sam']
     #     fs=FileSystemStorage()
     #     file=fs.save(image.name,image)
     #     file_url=fs.url(file)                
    return render(request,"imgupload.html")

def img_display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image=request.FILES['sam']
        print(image)
        fs=FileSystemStorage()
        file=fs.save(image.name,image)
        file_url=fs.url(file)
    return render(request,"imgdisplay.html",context={'file_url':file_url})

def upload(request):
    return render(request,"upload.html")
from myapp.utilities import store_image
def display(request):
    file_url=False
    if request.method=="POST" and request.FILES:
        image1=request.FILES.get('sam1')
        image2=request.FILES.get('sam2')
        file_urls=map(store_image,[image1,image2])
    return render(request,"display.html",context={'file_urls':file_urls})

from myapp import forms
def builtin(request):
    form=forms.SampleForm()
    return render(request,'builtin.html',{'form':form})
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block title %}
    <title> my BASE page</title>
  {% endblock %}

  <!-- below is bootstrap cdn which works only when internet is on -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script> -->
   

  <!-- below is bootstrap downloaded files combintion of css and js(which works when internet off also)-->

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    

    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body>
  {% include "partials/_topbar.html" %}
  {% include "partials/_navbar.html" %}
 
 {% block content %}
   <div class="container">
     <div class="jumbotron">
         <h1>Welcome to base page</h1>
         <img src="{% static 'images/pic2.jpg' %}" alt="image not found">
         <img src="{% static 'images/pic3.jpg' %}" alt="image not found">

     </div>
   </div>
 {% endblock %}
 {% include "partials/_footer.html" %}
</body>
</html>

templates/builtin.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>builtin-forms</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
  <form method="POST">
    {% csrf_token %}
    <!-- {{form.as_p}}
    <table border="2pt"
     {{form.as_table}}
     {{ form.as_ul }} 
  </table> -->


  <!-- <table>
    {{ form.as_table }}
  </table> -->
  <table border="2pt">
    {{ form|crispy }}
  </table>
    <input type="submit" value="Submit">
  </form>
</body>
</html>

templates/display.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User image display</title>
</head>
<body>
  {% for file_url in file_urls %}
  {% if file_url %}
    <img src="{{ file_url }}" alt="image not found" height="50%" width="50%">
  {% endif %}
  {% endfor %}
</body>
</html>

templates/get_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GET Demo Page</title>
</head>
<body>
    <form method="GET">
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
    <h1>entered username is {{name}}</h1>
</body>
</html>

templates/imgdisplay.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>User image display</title>
</head>
<body>
  {% if file_url %}
    <img src="{{ file_url }}" alt="image not found" height="50%" width="50%">
  {% endif %}
</body>
</html>

templates/imgupload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image uplaod</title>
</head>
<body>
    <form method="POST" action="{% url 'myapp:img_disp'%}" enctype="multipart/form-data">
        {% csrf_token %}
        Image:<input type="file" name="sam" id="sam">
        <input type="submit" value="Submit">
    </form>
    {% if file_url %}
      <img src="{{ file_url }}" alt="No image found" height="100" width="200">
    {% endif %}
</body>
</html>

templates/multiselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MultiSelect and Checkboxes</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="langauges">Choose Your Language:</label>
        <select name="language" id="languages" multiple>
            <option value="Python">Python</option>
            <option value="Java">Java</option>
            <option value="C#">C#</option>
            <option value="C">C Langauge</option>
            <option value="C++">C++</option>
        </select><br>
        <h6>Choose Your Food</h6>
        <label for="idli">
            Idli
        </label>
        <input type="checkbox" name="food" id="idli" value="IDLI">
        <label for="vada">
            vada
        </label>
        <input type="checkbox" name="food" id="vada" value="VADA">
        <label for="dosa">
            Dosa
        </label>
        <input type="checkbox" name="food" id="Dosa" value="DOSA">
        <label for="upma">
            upma
        </label>
        <input type="checkbox" name="food" id="upma" value="UPMA">
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
 <title>Home Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to the Home page</h1>
        </div>
      </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>Profile Page</title>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="jumbotron">
            <h1>Welcome to {{name}} Profile page</h1>
        </div>
      </div>
{% endblock %}

templates/partials/_footer.html
<!-- footer -->
<div class="alert alert-primary" role="alert">
  <center>Footer <br> 
  <h3>Navyaaaa!!!!!</h3></center>
</div>

templates/partials/_navbar.html
<!-- navbar -->
<div class="container">
  <ul class="nav">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
      </li>   
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:register' %}">Register</a>
      </li>      
  </ul>
</div>

templates/partials/_topbar.html
<!-- topbar -->
<div class="alert alert-secondary" role="alert">
  <center>Top Bar</center> 
</div>

templates/post_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>POST Demo page</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <label for="name">Name:</label>
        <input type="text" name="name" id="name">
        <input type="submit" value="Submit">
    </form>
   
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Upload</title>
</head>
<body>
  <form action="{% url 'myapp:display' %}" method="POST" enctype="multipart/form-data">
   {% csrf_token %}
   image1:<input type="file" name='sam1' id='sam1'>
   image2:<input type="file" name='sam2' id='sam2'>
   <input type="submit" value="submit">
  </form>
</body>
</html>